### PR TITLE
3.0.0.pre2

### PR DESCRIPTION
**Pull request by mikz**
- lock listen gem & fix integration
- use cross platform notification
- cleanup whitespace
- fix specs
- allow `.kick` folder in current working directory
- remove 1.8 support (at least in tests)

### CODE REVIEW

**Comment by alloy** [comment]
This looks really good. Thanks!

I’m only seeing some warnings on MRI 1.8.7 (the OS X default system installation):

```
/Library/Ruby/Gems/1.8/gems/notify-0.5.1/lib/notify/version.rb:2: warning: already initialized constant VERSION
```

(And some noise when running the test suite.)

If you can fix those, the gem should be good to be pushed. However, I will be gone for the next week, so in order to not stop the current attention you’re giving Kicker, I’m giving you push access to the repo and the gem. Feel free to push code and gems at your own leisure :)

**Comment by alloy** [comment]
If you already have a rubygems.org account, can you give me the email address I should use:

```
~/C/R/kicker [mikz-3.0.0] » gem owner kicker -a 'michal@o2h.cz'
Pushing gem to https://rubygems.org...
Owner could not be found.
```

**Comment by mikz** [comment]
Thanks! Try the one here http://rubygems.org/profiles/mikz

Odesláno z iPhonu
1. 6. 2013 v 22:37, Eloy Durán notifications@github.com:

**Comment by alloy** [comment]
Ah of course, I’m too tired to apply some logic ;)

Added you, thanks again for your work.

**Comment by mikz** [comment]
Thanks for the trust!

Odesláno z iPhonu
1. 6. 2013 v 22:52, Eloy Durán notifications@github.com:

**Comment by Manfred** [comment]
I'm fine with removing support for 1.8 in 3.0. We should mention that you can use < 3.0 when you need 1.8 support in the README.

**Comment by mikz** [comment]
@alloy 
- the warning is from notify's gemfile. It has been fixed but hasn't been released yet
- the stdout is silenced for some tests which were doing some outputting

**Comment by alloy** [comment]
@Manfred @mikz :+1:

**Pull request merged**
