### PR TITLE
I can haz 1.3.1 release to include patch for multibyte char problem?

### PR DESCRIPTION
**Pull request by timcharper**
Includes patch to fix invalid multibyte char problem encountered in Ruby 1.9.2

### CODE REVIEW

**Comment by timcharper** [comment]
Actually.. never mind this.  Seems like you're waiting on this https://github.com/alloy/kicker/issues/12 to release the patch, since you can't use kicker with ruby 1.9.2 with the current rucola dep.

:)

As you were, sorry for the noise.

**Comment by alloy** [comment]
Hey, yeah indeed, I think I’ll just have to write a simple C ext soon which uses FSEvents without RubyCocoa. Actually the multibyte issue that was fixed wasn't fixed in the right way, we should just have added a magic encoding comment to the file.

Since I’m attending a conference this weekend I’m not suer if I’ll get around to it this weekend, but otherwise I’ll try to do that on tuesday.

**Comment by timcharper** [comment]
Does this gem already do it? https://github.com/thibaudgg/rb-fsevent ?

If so, would a new c-extension be necessary?

**Comment by alloy** [comment]
Thanks, @Manfred used that gem to make Kicker work on different rubies and we’ve pushed 2.3.1. Thanks for bringing it back to my attention on the right time! :)

**Pull request closed without merging**
