### PR TITLE
rspec command name change

### PR DESCRIPTION
**Pull request by imajes**
rails 3 and rspec 2 changed the name of the spec command to rspec. this is a preliminary commit to support that... i'm also considering some updates to the readme but wanted to get some comments to ensure i wasn't doing it wrong. :)

thx

### CODE REVIEW

**Comment by alloy** [comment]
I don't use rspec, so if it works for you this way, then it’s good for me. Were you first gonna do more/README updates? Or should I already pull this in?

**Comment by imajes** [comment]
Hang tight, i want to investigate using rspec from gem rather than
some kind of bundler wrapper too. thanks!

On Fri, Mar 18, 2011 at 4:26 AM, alloy
reply@reply.github.com
wrote:

> I don't use rspec, so if it works for you this way, then it’s good for me. Were you first gonna do more/README updates? Or should I already pull this in?

**Comment by azisaka** [comment]
I think it should be merged. It's an important change.

**Comment by Manfred** [comment]
Didn't merge because the patch didn't fix the tests. But it has been applied.

**Pull request closed without merging**
